### PR TITLE
changes to view auditlogs by project role users

### LINKED ISSUE #225: PROJECT_ADMIN/CLUSTER_ADMIN/CLUSTER_ADMIN_READONLY roles not able to view audit logs
### Expected vs actual behavior
User/Groups with the following roles should be able to view audit-logs for that paticular project and cluster
PROJECT_ADMIN/CLUSTER_ADMIN/CLUSTER_ADMIN_READONLY 
-

### Steps to reproduce the bug

1. Create/Add new User/Group in Paralus Dashbaord
2. Assign one of the above mentioned roles to User/Group
3. Check audit-logs section in dashboard

### Are you using the latest version of the project? Yes

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

- NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
paralus paralus         5               2023-05-22 06:09:11.808502642 +0000 UTC deployed        ztka-0.2.4      v0.2.3

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

kubectl version --output=yaml
clientVersion:
  buildDate: "2021-01-13T13:23:52Z"
  compiler: gc
  gitCommit: 1dd5338295409edcfff11505e7bb246f0d325d15
  gitTreeState: clean
  gitVersion: v1.19.7
  goVersion: go1.15.5
  major: "1"
  minor: "19"
  platform: windows/amd64
serverVersion:
  buildDate: "2023-04-15T00:32:27Z"
  compiler: gc
  gitCommit: cd5c12c51b0899612375453f7a7c2e7b6563f5e9
  gitTreeState: clean
  gitVersion: v1.23.17-eks-0a21954
  goVersion: go1.19.6
  major: "1"
  minor: 23+
  platform: linux/amd64
==========================
- Paralus is installed on EKS cluster.

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [ ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [ ] I'm using the latest version of the project.

### PR DESCRIPTION
**Pull request by niravparikh05**
### What does this PR change?

- Fixes #225 

### Does the PR depend on any other PRs or Issues? If yes, please list them.

- 

### Checklist

I confirm, that I have...

- [ ] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

### CODE REVIEW

File: internal/provider/kratos/kratos.go [hunk 1]
```diff
@@ -16,16 +18,19 @@ import (
...
+	Partner      string
 }
 
 type kratosAuthProvider struct {
 	kc *kclient.APIClient
 }
 type AuthProvider interface {
 	// create new user
-	Create(context.Context, string, map[string]interface{}, bool) (string, error) // returns id,error
+	Create(context.Context, string, map[string]interface{}, map[string]interface{}) (string, error) // returns id,error
```
Comment (akshay196) [inline internal/provider/kratos/kratos.go:31]: Can we use `IdentityPublicMetadata` instead of map as parameter for Create and Update function?
I think this will make use Organization/Partner/ForceReset directly without need to converting interface{} to their types.

File: pkg/service/audit_log.go [hunk 2]
```diff
@@ -1,40 +1,117 @@
...
+		}
+		if !available {
+			matchesAll = false
+			prerr = errors.Join(prerr, fmt.Errorf("not authorized for project %s", rproject))
+		}
+	}
+	if !matchesAll {
+		return prerr
+	}
+	return prerr
```
Comment (akshay196) [inline pkg/service/audit_log.go:116]: Can we rewrite
```go
        if !matchesAll {
		return prerr
	}
	return prerr
```
to only 
```go
    return prerr
```
?

**Review by akshay196 — CHANGES_REQUESTED** [review]
Just minor suggestions. @niravparikh05

File: internal/provider/kratos/kratos.go (hunk 1 above)
Comment (niravparikh05) [reply internal/provider/kratos/kratos.go]: @akshay196 this is taken care of

**Review by akshay196 — APPROVED** [review]

**Comment by akshay196** [comment]
@niravparikh05 Are we good to merge this PR? Let's squash and merge with conventional commit message.

**Comment by akshay196** [comment]
@niravparikh05 Please follow the commit message convention as explained here - https://github.com/paralus/paralus/blob/main/CONTRIBUTING.md#commit-message-guidelines
