### PR TITLE
Fixed error code and message for non exist projects name in GET cluster API

### LINKED ISSUE #142: Project Name In API Doesn't Matter
### Expected vs actual behavior

After a cluster has been created, if you then make a call to get the information or to delete the cluster with a random project name, it still works. It should report that the cluster does not exist. This has created problems where the project gets deleted but the cluster still exists, and then the cluster could not be deleted, which is a separate issue: https://github.com/paralus/paralus/issues/141

### Steps to reproduce the bug

1. Create a project + cluster
2. Call the GetCluster API call with a generic or non-existent project name
3. API information is returned

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

```
VERSION: 0.1.0
BUILD: 0.1.0
BUILD-TIME: 1656329967
ARCH: darwin/amd64
```

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

Kubectl
```
clientVersion:
  buildDate: "2022-08-23T17:44:59Z"
  compiler: gc
  gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2
  gitTreeState: clean
  gitVersion: v1.25.0
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-29T18:41:42Z"
  compiler: gc
  gitCommit: 52e500d139bdef42fbc4540c357f0565c7867a81
  gitTreeState: clean
  gitVersion: v1.22.16-eks-ffeb93d
  goVersion: go1.16.15
  major: "1"
  minor: 22+
  platform: linux/amd64

```

Helm
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

Project name needs to be checked before anything dealing with a cluster

- [X ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [X ] I'm using the latest version of the project.

### PR DESCRIPTION
**Pull request by hiteshwani29**
### What does this PR change?

- Fix error code and message for GET cluster API when a non-existing project name is passed to API.
- Fixes #142 

### Does the PR depend on any other PRs or Issues? If yes, please list them.

- No

### Checklist

I confirm, that I have...

- [x] Read and followed the contributing guide in `CONTRIBUTING.md`
- [x] Added tests for this PR
- [x] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [x] Updated `CHANGELOG.md`

### CODE REVIEW

File: pkg/service/cluster.go [hunk 1]
```diff
@@ -718,6 +720,9 @@ func (cs *clusterService) List(ctx context.Context, opts ...query.Option) (*infr
 	var proj models.Project
 	_, err := dao.GetByName(ctx, cs.db, queryOptions.Project, &proj)
 	if err != nil {
+		if err == sql.ErrNoRows {
+			return nil, status.Error(codes.NotFound, fmt.Sprintf("Project %v not found.", queryOptions.GetProject()))
```
Comment (akshay196) [inline pkg/service/cluster.go:724]: Can you change error message to something generic like `cluster not found` or `requested resource not found`?

A less privileged user (for example, project or namespace read only) who cannot retieve full projects list can determine existence of project with the help of error message.

Comment (akshay196) [reply pkg/service/cluster.go:724]: There are places where we return project name in error message which need to removed too. Let's take it separately.
cc @niravparikh05

**Review by akshay196 — CHANGES_REQUESTED** [review]
Just one minor change:

**Review by akshay196 — APPROVED** [review]

File: pkg/service/cluster.go (hunk 1 above)
Comment (akshay196) [reply pkg/service/cluster.go]: Update PR with new error message. Also added a test case to cover non-exists project scenario.
