### PR TITLE
fix project id is recorded as part of cluster related auditlogs

### LINKED ISSUE #121: In one of the cluster update flows project id is recoded as part of auditlogs
### Expected vs actual behavior

- During one of the cluster update flows project id is recoded as part of auditlogs

### Steps to reproduce the bug

1. Install paralus, create an imported cluster, perform kubectl and few actions on it, then delete the cluster.
2. Check the audit logs, we can see in one of the cluster update audit entry project id is recorded instead of name

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

- Yes

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.

### PR DESCRIPTION
**Pull request by niravparikh05**
### What does this PR change?

- Fixes #121 

### Does the PR depend on any other PRs or Issues? If yes, please list them.

- No

### Checklist

I confirm, that I have...

- [x] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [x] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [x] Updated `CHANGELOG.md`

### CODE REVIEW

File: pkg/service/cluster.go [hunk 1]
```diff
@@ -596,6 +596,13 @@ func (s *clusterService) Update(ctx context.Context, cluster *infrav3.Cluster) (
 		h.OnChange(ev)
 	}*/
 
+	if id, err := uuid.Parse(projectName); err == nil {
```
Comment (mabhi) [inline pkg/service/cluster.go:599]: This looks good. This safeguards us irrespective of whether project name or id is present in the `projectName` variable. Just curious as to when/why are we passing project id instead of name.

**Review by mabhi — APPROVED** [review]
