### PR TITLE
User last access time

### LINKED ISSUE #84: Last Access time is not available on the user endpoint
### Expected vs actual behavior

- Last access time should be shown per user depending on when the last logged in Paralus application

### Steps to reproduce the bug

1. Go to users list screen from main menu

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

- Yes

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

- Reproducible anywhere

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

- Need to enhance the user endpoint and fetch the last access information from kratos.

- [ ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [ ] I'm using the latest version of the project.

### PR DESCRIPTION
**Pull request by akshay196**
### What does this PR change?
Add last access time in User API

### Does the PR depend on any other PRs or Issues? If yes, please list them.

Fix #84 

### Checklist

I confirm, that I have...

- [ ] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

### CODE REVIEW

**Comment by akshay196** [comment]
Sample response:
```
$ curl 'localhost:11000/auth/v3/user/admin@paralus.local?partner=partner&organization=org' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   450  100   450    0     0  31010      0 --:--:-- --:--:-- --:--:-- 32142
{
  "apiVersion": "system.k8smgmt.io/v3",
  "kind": "User",
  "metadata": {
    "name": "admin@paralus.local",
    "id": "e14e17af-a5d6-4547-87d4-20a99e3d5ce0",
    "modifiedAt": {
      "seconds": 1665126478,
      "nanos": 809825000
    }
  },
  "spec": {
    "firstName": "admin",
    "lastName": "user",
    "groups": [
      "Organization Admins",
      "All Local Users"
    ],
    "idpGroups": [
      ""
    ],
    "projectNamespaceRoles": [
      {
        "role": "ADMIN",
        "group": "Organization Admins"
      }
    ],
    "lastLogin": "2022-10-14T11:12:27+05:30"
  },
  "status": {
    "conditionStatus": 2
  }
}

```

File: pkg/service/utils.go [hunk 1]
```diff
@@ -33,3 +35,18 @@ func IsInternalRequest(ctx context.Context) bool {
...
 }
+
+// getLastLoginTime return latest authenticated time from sessions.
+func getLastLoginTime(sessions []models.KratosSessions) time.Time {
+	var auths []int64
+	for _, s := range sessions {
+		auths = append(auths, s.AuthenticatedAt.UnixMilli())
+	}
+	latest := auths[0]
+	for _, auth := range auths {
```
Comment (niravparikh05) [inline pkg/service/utils.go:46]: why can't we just do a select max of ( utilize postgres functions ) to achieve this. It would have a better performance as we can avoid couple of iterations and conversions as well.

**Review by niravparikh05 — COMMENTED** [review]
why don't we incorporate the entire logic in postgres query itself.

File: pkg/service/utils.go (hunk 1 above)
Comment (akshay196) [reply pkg/service/utils.go]: Fixed.

**Review by niravparikh05 — DISMISSED** [review]
lgtm

**Review by niravparikh05 — APPROVED** [review]
lgtm
